# Use the official Node.js image
FROM node:20.15.0

# Set the working directory inside the container
WORKDIR /srv/client

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3000 for the React development server
EXPOSE 3000

# Start the React development server with live reloading
CMD ["npm", "start"]