services:
  omnidownloader:
    image: omnidownloader:latest
    container_name: omnidownloader
    environment:
      - DEBUG=true
      - SEPARATE_FOLDERS=true
      - IMAGE_FOLDER=images
      - VIDEO_FOLDER=videos
    volumes:
      - ./Data:/Data:rw # Configuration files
      - ./downloads:/downloads:rw # Downloaded files
    ports:
      - "6969:6969"
    network_mode: bridge