services:
  omnidownloader-backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: omnidownloader-backend
    environment:
      - DEBUG=true
      - SEPARATE_FOLDERS=true
      - IMAGE_FOLDER=images
      - VIDEO_FOLDER=videos
    volumes:
      - ./server:/srv/OmniDownloader  # Mount the entire backend codebase for live reloading
      - /srv/OmniDownloader/node_modules  # Avoids overwriting node_modules with the host
    ports:
      - "6969:6969"
    networks:
      - omnidownloader

  omnidownloader-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: omnidownloader-frontend
    environment:
      - PUBLIC_URL=/
    command: ["npm", "start"]
    volumes:
      - ./client:/srv/client
      - /srv/client/node_modules  # Avoids overwriting node_modules with the host
    ports:
      - "3000:3000"
    networks:
      - omnidownloader