blank_issues_enabled: false
contact_links:
  - name: OmniDownloader Support
    url: https://discord.benwhybrow.com/
    about: If you require support, please use this Discord server and create a ticket for help.
