# Use Node.js image
FROM node:20.15.0

# Install Nano and file-watching tool
RUN apt-get update && apt-get install -y nano
RUN npm install -g nodemon

# Set the working directory inside the container
WORKDIR /srv/OmniDownloader

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the backend port
EXPOSE 6969

# Use nodemon to automatically restart the server on changes
CMD ["npm", "run", "dev"]